kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-view-access
  namespace: hackweb
rules:
- apiGroups: ["*"] # "*" indicates all
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-edit-access
  namespace: hackweb
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"] # verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-view-access
  namespace: hackapi
rules:
- apiGroups: ["*"] # "*" indicates all
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit-access
  namespace: hackapi
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]